# docs: https://rust-lang.github.io/rustfmt/
format_code_in_doc_comments = true   # nightly
group_imports               = "One"  # nightly
imports_granularity         = "One"  # nightly
match_block_trailing_comma  = true
max_width                   = 100
use_small_heuristics        = "Off"
